import type { Metadata } from 'next'
import './globals.css'
import NextTopLoader from 'nextjs-toploader'
import LayoutWrapper from '@/components/LayoutWrapper' // Import the client component

export const metadata: Metadata = {
  title: 'QuickGigs',
  description: 'Generated by create next app',
  icons:{
    icon:['/favicon.ico?v=4']
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
          <NextTopLoader
            color="#000000"
            initialPosition={0.08}
            crawlSpeed={150}
            height={4}
            crawl={true}
            showSpinner={false}
            easing="ease-in-out"
            speed={300}
            zIndex={1600}
            showAtBottom={false}
          />
          {/* Wrap the main layout inside LayoutWrapper */}
          <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  )
}
