import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components";
import LeftSidebar from "@/components/LeftSidebar";
import RightSidebar from "@/components/RightSidebar";
import NextTopLoader from "nextjs-toploader";

export const metadata: Metadata = {
  title: "QuickGigs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader
          color="#6A0DAD"
          initialPosition={0.08}
          crawlSpeed={150}
          height={4}
          crawl={true}
          showSpinner={false}
          easing="ease-in-out"
          speed={300}
          zIndex={1600}
          showAtBottom={false}
        />
        {/* Header */}
        <Header />

        {/* Main Layout with Sidebars */}
        <div className="flex h-screen pt-[50px]">
          <LeftSidebar />

          {/* Main Content */}
          <main className="flex justify-center mx-auto max-w-5xl min-h-screen">
            {children}
          </main>

          {/* Right Sidebar */}
          <RightSidebar />
        </div>
      </body>
    </html>
  );
}
